//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroLoadBalancerListenerAttachment) DeepCopyInto(out *HeroLoadBalancerListenerAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroLoadBalancerListenerAttachment.
func (in *HeroLoadBalancerListenerAttachment) DeepCopy() *HeroLoadBalancerListenerAttachment {
	if in == nil {
		return nil
	}
	out := new(HeroLoadBalancerListenerAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeroLoadBalancerListenerAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroLoadBalancerListenerAttachmentInitParameters) DeepCopyInto(out *HeroLoadBalancerListenerAttachmentInitParameters) {
	*out = *in
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CertificateSecretsName != nil {
		in, out := &in.CertificateSecretsName, &out.CertificateSecretsName
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.OverprovisioningFactor != nil {
		in, out := &in.OverprovisioningFactor, &out.OverprovisioningFactor
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupArn != nil {
		in, out := &in.TargetGroupArn, &out.TargetGroupArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroLoadBalancerListenerAttachmentInitParameters.
func (in *HeroLoadBalancerListenerAttachmentInitParameters) DeepCopy() *HeroLoadBalancerListenerAttachmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(HeroLoadBalancerListenerAttachmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroLoadBalancerListenerAttachmentList) DeepCopyInto(out *HeroLoadBalancerListenerAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HeroLoadBalancerListenerAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroLoadBalancerListenerAttachmentList.
func (in *HeroLoadBalancerListenerAttachmentList) DeepCopy() *HeroLoadBalancerListenerAttachmentList {
	if in == nil {
		return nil
	}
	out := new(HeroLoadBalancerListenerAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HeroLoadBalancerListenerAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroLoadBalancerListenerAttachmentObservation) DeepCopyInto(out *HeroLoadBalancerListenerAttachmentObservation) {
	*out = *in
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CertificateSecretsName != nil {
		in, out := &in.CertificateSecretsName, &out.CertificateSecretsName
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.OverprovisioningFactor != nil {
		in, out := &in.OverprovisioningFactor, &out.OverprovisioningFactor
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupArn != nil {
		in, out := &in.TargetGroupArn, &out.TargetGroupArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroLoadBalancerListenerAttachmentObservation.
func (in *HeroLoadBalancerListenerAttachmentObservation) DeepCopy() *HeroLoadBalancerListenerAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(HeroLoadBalancerListenerAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroLoadBalancerListenerAttachmentParameters) DeepCopyInto(out *HeroLoadBalancerListenerAttachmentParameters) {
	*out = *in
	if in.AlpnPolicy != nil {
		in, out := &in.AlpnPolicy, &out.AlpnPolicy
		*out = new(string)
		**out = **in
	}
	if in.CertificateSecretsName != nil {
		in, out := &in.CertificateSecretsName, &out.CertificateSecretsName
		*out = new(string)
		**out = **in
	}
	if in.EnableDeletionProtection != nil {
		in, out := &in.EnableDeletionProtection, &out.EnableDeletionProtection
		*out = new(bool)
		**out = **in
	}
	if in.LoadBalancerID != nil {
		in, out := &in.LoadBalancerID, &out.LoadBalancerID
		*out = new(string)
		**out = **in
	}
	if in.OverprovisioningFactor != nil {
		in, out := &in.OverprovisioningFactor, &out.OverprovisioningFactor
		*out = new(float64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.TargetGroupArn != nil {
		in, out := &in.TargetGroupArn, &out.TargetGroupArn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroLoadBalancerListenerAttachmentParameters.
func (in *HeroLoadBalancerListenerAttachmentParameters) DeepCopy() *HeroLoadBalancerListenerAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(HeroLoadBalancerListenerAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroLoadBalancerListenerAttachmentSpec) DeepCopyInto(out *HeroLoadBalancerListenerAttachmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroLoadBalancerListenerAttachmentSpec.
func (in *HeroLoadBalancerListenerAttachmentSpec) DeepCopy() *HeroLoadBalancerListenerAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(HeroLoadBalancerListenerAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeroLoadBalancerListenerAttachmentStatus) DeepCopyInto(out *HeroLoadBalancerListenerAttachmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeroLoadBalancerListenerAttachmentStatus.
func (in *HeroLoadBalancerListenerAttachmentStatus) DeepCopy() *HeroLoadBalancerListenerAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(HeroLoadBalancerListenerAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}
