name: OrographicLift/hlb
resources:
    Xplane Resource - terraform-provider-zonehero:
        subCategory: ""
        name: Xplane Resource - terraform-provider-zonehero
        title: Xplane Resource - terraform-provider-zonehero
        argumentDocs:
            docs/index.md: )
            docs/resources/*.md: )
        importStatements: []
